-- Create products table
CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    image_url TEXT NOT NULL,
    category VARCHAR(50) NOT NULL
);

-- Truncate existing products (optional)
TRUNCATE TABLE products;

-- Insert seed data
INSERT INTO products (name, price, image_url, category) VALUES
('marie', 20.0, 'image/marie.webp', 'top_buys'),
('bourbon', 50.0, 'image/bourbon.webp', 'top_buys'),
('coconut', 35.0, 'image/coconut.jpeg', 'top_buys'),
('godrej no.1', 10.0, 'image/no.1.jpg', 'top_buys'),
('lifebuoy', 10.0, 'image/lifebuoy.jpg', 'top_buys'),
('vim bar', 25.0, 'image/vim.jpg', 'top_buys'),
('bounce cream', 10.0, 'image/bounce.webp', 'top_buys'),
('tiger', 10.0, 'image/tiger.webp', 'top_buys'),
('happy happy', 25.0, 'image/happy happy.jpg', 'top_buys'),
('milk 1L', 68.0, 'image/milk-dp1.jpg', '1dairyproducts'),
('paneer 100gm', 40.0, 'image/paneer-dp2.webp', '1dairyproducts'),
('Taak 1L', 30.0, 'image/taak-dp3.webp', '1dairyproducts'),
('dahi 1L', 75.0, 'image/dahi-dp4.jpg', '1dairyproducts'),
('ShriKhand 250gm', 80.0, 'image/shrikhand-dp5.webp', '1dairyproducts'),
('Basundi 250ml', 100.0, 'image/basundi-dp6.jpg', '1dairyproducts'),
('Butter 100gm', 100.0, 'image/butter-dp7.webp', '1dairyproducts'),
('eggs per dozen', 72.0, 'image/eggs-dp8.jpg', '1dairyproducts'),
('Bounce cream', 10.0, 'image/bounce.webp', '2biscut'),
('parle-G', 20.0, 'image/parleG.jpg', '2biscut'),
('marie', 10.0, 'image/marie.webp', '2biscut'),
('bourbon', 50.0, 'image/bourbon.webp', '2biscut'),
('oreo', 40.0, 'image/oreo.jpg', '2biscut'),
('hide and seek', 30.0, 'image/hide and seek.jpg', '2biscut'),
('coconut', 35.0, 'image/coconut.jpeg', '2biscut'),
('good day', 20.0, 'image/good day.webp', '2biscut'),
('happy happy', 25.0, 'image/happy happy.jpg', '2biscut'),
('zig-zag', 15.0, 'image/zigzag.webp', '2biscut'),
('Dark Fantasy', 35.0, 'image/dark fantecy.webp', '2biscut'),
('tiger', 10.0, 'image/tiger.webp', '2biscut'),
('bread', 30.0, 'image/bread-bp10.webp', '2biscut'),
('cream bun', 45.0, 'image/creambun-bp11.jpg', '2biscut'),
('bunpav', 25.0, 'image/bunpav-bp12.jpg', '2biscut'),
('cream roll', 50.0, 'image/creamroll-dp13.webp', '2biscut'),
('nice time', 25.0, 'image/nice time.jpg', '2biscut'),
('GS tea 250gm', 140.0, 'image/tea-pp1.webp', '3powder'),
('redlebel 250gm', 155.0, 'image/redlabel-pp2.jpg', '3powder'),
('bru cofee 50gm', 250.0, 'image/bru-pp3.webp', '3powder'),
('nescafe 50gm', 299.0, 'image/nescafe-pp4.webp', '3powder'),
('bourn vita 200gm', 130.0, 'image/bournvita-pp5.jpg', '3powder'),
('bele tea 100gm', 90.0, 'image/bele-pp6.jpg', '3powder'),
('medimix', 45.0, 'image/medimix.jpeg', '4bathingsoap'),
('dettole', 35.0, 'image/dettole.webp', '4bathingsoap'),
('rexona', 50.0, 'image/rexona.jpg', '4bathingsoap'),
('godrj no.1', 30.0, 'image/no.1.jpg', '4bathingsoap'),
('cinthol', 25.0, 'image/cinthol.jpg', '4bathingsoap'),
('dove', 33.0, 'image/dove.jpeg', '4bathingsoap'),
('lux', 27.0, 'image/lux-s6.webp', '4bathingsoap'),
('lifebuoy', 29.0, 'image/lifebuoy.jpg', '4bathingsoap'),
('santoor', 32.0, 'image/santoor-s1.webp', '4bathingsoap'),
('surfexcel', 75.0, 'image/surfexcel.jpeg', '5cleaning'),
('tide', 67.0, 'image/tide.jpeg', '5cleaning'),
('sargam', 20.0, 'image/sargam-c3.jpg', '5cleaning'),
('wheel powder', 72.0, 'image/wheel-c1.webp', '5cleaning'),
('nirma', 45.0, 'image/nirma-c2.webp', '5cleaning'),
('wheel', 25.0, 'image/wheel.jpg', '5cleaning'),
('sargam powder', 53.0, 'image/sargam-powder-c4.jpg', '5cleaning'),
('vim bar', 70.0, 'image/vim.jpg', '5cleaning'),
('vim scruber', 50.0, 'image/vimscrub.jpeg', '5cleaning'),
('rin', 105.0, 'image/rin.webp', '5cleaning'),
('gala scruber', 20.0, 'image/gala-c5.webp', '5cleaning'),
('clinicplus', 230.0, 'image/clinicplus-h1.webp', '6shampoo'),
('head and sholder', 180.0, 'image/h&s-h2.webp', '6shampoo'),
('sunsilk', 135.0, 'image/sunsilk-h4.webp', '6shampoo'),
('dove', 68.0, 'image/dove-h3.webp', '6shampoo'),
('parashute oil', 65.0, 'image/parashute-h5.webp', '6shampoo'),
('navratna', 47.0, 'image/navratna-h7.jpg', '6shampoo'),
('jasmin oil', 83.0, 'image/jasmin-h6.webp', '6shampoo'),
('tur dal', 100.0, 'image/tur dal-dl1.webp', '7cereles'),
('moong dal', 140.0, 'image/moong-dal-dl2.webp', '7cereles'),
('chana dal', 100.0, 'image/chana-daal-dl3.jpg', '7cereles'),
('masoor dal', 110.0, 'image/masoor dal-dl4.jpg', '7cereles'),
('masoor', 100.0, 'image/masoor-dl6.jpg', '7cereles'),
('urad dal', 120.0, 'image/uraddal-dl7.webp', '7cereles'),
('shengdana', 120.0, 'image/shengdana-dl8.jpg', '7cereles'),
('Sabudana', 112.0, 'image/shabudana-dl10.jpg', '7cereles'),
('rava', 100.0, 'image/rava-dl11.jpg', '7cereles'),
('maida', 100.0, 'image/maida-dl12.jpg', '7cereles'),
('apsara pencil', 6.0, 'image/apsara pensil-s1.jpg', '8stestionary'),
('nataraj pencil', 5.0, 'image/nataraj pencil-s2.webp', '8stestionary'),
('cello gripper pen', 10.0, 'image/cello-gripper-pen-s3.webp', '8stestionary'),
('reynolds', 10.0, 'image/reynolds-s4.avif', '8stestionary'),
('nataraj sharpener', 4.0, 'image/NatarajPencilSharpener-s6.webp', '8stestionary'),
('eraser', 3.0, 'image/eraser-s7.avif', '8stestionary'),
('apsara eraser', 4.0, 'image/apsara eraser-s8.webp', '8stestionary'),
('sharpner', 5.0, 'image/sharpner-s9.webp', '8stestionary'),
('Notebook', 80.0, 'image/notebook-s10.webp', '8stestionary'),
('salted chips', 10.0, 'image/salted-sn1.jpg', '9snacks'),
('cream onion', 10.0, 'image/cream onion-sn2.jpg', '9snacks'),
('tomato chips', 10.0, 'image/tomato-sn3.jpg', '9snacks'),
('chataka pataka', 10.0, 'image/chataka pataka-sn4.jpg', '9snacks'),
('flaminhot', 10.0, 'image/flaminhot -sn6.jpg', '9snacks'),
('wheels', 10.0, 'image/wheels-sn8.webp', '9snacks'),
('maggi', 10.0, 'image/maggi-sn10.webp', '9snacks'),
('yippee', 10.0, 'image/yippee-sn11.webp', '9snacks'),
('gippi', 10.0, 'image/gippi-sn12.webp', '9snacks'),
('coriander', 15.0, 'image/coriander-f1.jpg', '10fromfarm'),
('potatoes', 40.0, 'image/product-5.png', '10fromfarm'),
('curry leaves', 10.0, 'image/curryleaves-f2.jpg', '10fromfarm'),
('green chilli', 160.0, 'image/green chilli-f3.webp', '10fromfarm'),
('tomatoes', 40.0, 'image/tomatoes-f8.jpg', '10fromfarm'),
('ginger', 200.0, 'image/Ginger-f4.avif', '10fromfarm'),
('onion', 60.0, 'image/onion-f5.jpg', '10fromfarm'),
('sprouts', 100.0, 'image/sprouts-f6.jpg', '10fromfarm'),
('garlic', 100.0, 'image/garlic-f6.avif', '10fromfarm'),
('peas', 120.0, 'image/Peas-f9.jpg', '10fromfarm');